### ISSUE TITLE
fs2-3 and cats-effect-3

### ISSUE THREAD

**Issue by blandflakes** [sovt/spata#16]
Hello! Was just wondering if there were plans to publish versions for fs2-3.x.x and cats-effect-3, or if contributions would be welcome for the same. We're migrating our systems and spata is one of our last holdouts.

**Comment by susuro** [comment]
Hi and sorry for responding with such delay. My notifications were incorrectly configured and I missed your message.
I have been planning to migrate spata to cats-effect 3 and fs2 3 together with Scala 3. This seems though to be a long journey to go because spata depends heavily on shapeless, including features that are not available (or at least not in the same form) for Scala 3.
However, if this helps you we may start by porting spata to cats and fs2 3 on Scala 2 and do the Scala 3 migration later.

**Comment by blandflakes** [comment]
No problem! This isn't an urgent move for us. We had the general sense that CE3 was going mainstream far faster than Scala 3, so we've been moving a lot of our services over to CE3. I could see an argument that we're making more work for ourselves by again having to do a Scala 3 migration, but we hope it will reduce the Scala 3 work in total.

We use fingo in a small fallback service where delaying the upgrade isn't too difficult. I'd personally rather wait until whatever makes sense for you all than put any pressure on a migration or trying to replace fingo; it's a nice simplifying part of the system for us.

**Comment by susuro** [comment]
I'm glad to hear this. I think that updating CE and FS2 first and then moving to Scala 3 is the best option for me, too. However, I would like to minimize incompatible releases, and both upgrades require such incompatibility.
The preliminary version of *spata* that compiles and runs with CE3 and FS2-3 is already available on `fs2-v3` branch. I'm going to complete this shift before starting with Scala 3 migration. It'll give us the option to make an intermediary release if required.

**Comment by susuro** [comment]
spata 3 for Scala 3, Cats Effect 3, and FS2 3 has been [published](https://central.sonatype.com/artifact/info.fingo/spata_3/3.0.0).
The version for Scala 2, Cats Effect 3, and FS2 3 is available on the branch [s2ce3](https://github.com/fingo/spata/tree/s2ce3) with updated documentation.
